"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { SiteHeader } from "@/components/site-header";
import { formatPrice } from "@/lib/products";

function CartContent() { const { items, total, removeItem } = useCart(); return <main className="mx-auto max-w-360 px-6 pb-24 md:px-12"><div className="mb-14 flex items-end justify-between"><div><p className="sans mb-4 text-[10px] uppercase tracking-[.2em] text-[var(--muted)]">Sua seleção</p><h1 className="display text-6xl md:text-8xl">Carrinho.</h1></div><span className="sans text-[11px] uppercase tracking-[.14em] text-[var(--muted)]">{items.length} item(ns)</span></div>{items.length === 0 ? <div className="border-y border-[var(--line)] py-16"><p className="text-3xl">Seu carrinho está esperando uma peça.</p><Link href="/#colecao" className="sans mt-8 inline-flex items-center gap-2 border-b border-[var(--ink)] pb-2 text-[11px] uppercase tracking-[.15em]">Ver coleção <ArrowRight size={14} /></Link></div> : <div className="grid gap-12 md:grid-cols-[1fr_340px]"><div>{items.map((item) => <div key={item.id} className="flex gap-5 border-b border-[var(--line)] py-5"><div className="product-wash h-28 w-24 shrink-0" /><div className="flex flex-1 justify-between"><div><h2 className="text-2xl">{item.name}</h2><p className="sans mt-2 text-[10px] uppercase tracking-[.1em] text-[var(--muted)]">{item.size} · {item.fit} · {item.color}</p><p className="sans mt-4 text-sm">{formatPrice(item.price)} × {item.quantity}</p></div><button onClick={() => removeItem(item.id)} aria-label={`Remover ${item.name}`}><Trash2 size={16} strokeWidth={1.5} /></button></div></div>)}</div><aside className="border-t border-[var(--ink)] pt-5"><div className="flex justify-between text-xl"><span>Total</span><span>{formatPrice(total)}</span></div><Link href="/checkout" className="mt-8 flex items-center justify-between bg-[var(--ink)] px-5 py-4 text-white"><span className="sans text-[11px] uppercase tracking-[.15em]">Continuar para checkout</span><ArrowRight size={16} /></Link></aside></div>}<Link href="/" className="sans mt-12 flex items-center gap-2 text-[10px] uppercase tracking-[.15em] text-[var(--muted)]"><ArrowLeft size={14} /> Continuar navegando</Link></main>; }
export default function CartPage() { return <><SiteHeader /><CartContent /></>; }
